# Generated by Django 5.2.14 on 2026-05-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип элемента',
                'verbose_name_plural': 'типы элементов',
            },
        ),
        migrations.CreateModel(
            name='LabElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('position', models.IntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('position', models.IntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'лабораторная работа',
                'verbose_name_plural': 'лабораторные работы',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'модуль',
                'verbose_name_plural': 'модули',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='ответ (для текстовых)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип теста',
                'verbose_name_plural': 'типы тестов',
            },
        ),
        migrations.CreateModel(
            name='ElementTypeBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.elementtype', verbose_name='тип элемента')),
                ('lab_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_bindings', to='lms.labelement', verbose_name='элемент')),
            ],
            options={
                'verbose_name': 'связь элемента с типом',
                'verbose_name_plural': 'связи элементов с типами',
                'unique_together': {('lab_element', 'element_type')},
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField(verbose_name='формула')),
                ('lab_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='lms.labelement', verbose_name='элемент')),
            ],
            options={
                'verbose_name': 'формула',
                'verbose_name_plural': 'формулы',
            },
        ),
        migrations.AddField(
            model_name='labelement',
            name='laboratory_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='lms.laboratorywork', verbose_name='лабораторная работа'),
        ),
        migrations.AddField(
            model_name='laboratorywork',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_works', to='lms.module', verbose_name='модуль'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='правильный')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответов',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.testtype', verbose_name='тип теста'),
        ),
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(default=0, verbose_name='порядок')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('instructions', models.TextField(blank=True, verbose_name='инструкция')),
                ('hint', models.TextField(blank=True, verbose_name='подсказка')),
                ('element_type_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lms.elementtypebinding', verbose_name='связь элемента с типом')),
            ],
            options={
                'verbose_name': 'шаг',
                'verbose_name_plural': 'шаги',
                'ordering': ['step_order'],
                'unique_together': {('element_type_binding', 'step_order')},
            },
        ),
        migrations.AddField(
            model_name='test',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lms.trainingstep', verbose_name='шаг'),
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='текстовое значение')),
                ('value_integer', models.IntegerField(blank=True, null=True, verbose_name='числовое значение')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='логическое значение')),
                ('value_formula', models.TextField(blank=True, null=True, verbose_name='формула')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.characteristic', verbose_name='характеристика')),
                ('element_type_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='lms.elementtypebinding', verbose_name='связь элемента с типом')),
            ],
            options={
                'verbose_name': 'значение характеристики',
                'verbose_name_plural': 'значения характеристик',
                'unique_together': {('element_type_binding', 'characteristic')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('step', 'sort_order')},
        ),
    ]
