# Generated by Django 5.2.14 on 2026-05-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingStep',
            new_name='Step',
        ),
        migrations.AlterUniqueTogether(
            name='characteristicvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='testtype',
            name='code',
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
    ]
