# Generated by Django 5.2.14 on 2026-06-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_trainingstep_step_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristicvalue',
            options={'ordering': ['order'], 'verbose_name': 'значение характеристики', 'verbose_name_plural': 'значения характеристик'},
        ),
        migrations.RemoveField(
            model_name='step',
            name='hint',
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='order',
            field=models.IntegerField(default=0, verbose_name='порядок'),
        ),
    ]
