# Generated by Django 5.2.14 on 2026-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_characteristicvalue_single_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='summary'),
        ),
    ]
